version: "3"
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diplom
      MYSQL_USER: alexander
      MYSQL_PASSWORD: root
    networks:
      - app-network

  app:
    build: 
      dockerfile: ./Docker/Dockerfile
      context: ../
    ports:
      - "80:3000"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      DATABASE_URL: "mysql://root:root@db:3306/diplom"
    command: >
      sh -c "
        sleep 10;
        npx prisma migrate deploy
        npm run dev
      "
    networks:
      - app-network

networks:
  app-network: